### ISSUE TITLE
Should we use `constrainmol` to handle bond constraints?

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/reproducibility_study#12]
It might be reasonable to use [`constrainmol`](https://github.com/rsdefever/constrainmol) to solve for our coordinates, especially for our constrained molecules, as this this will allow us to build up our molecules, parametrize them, and then use their `r_eq` values to define their bond lengths.

https://github.com/rsdefever/constrainmol/blob/0baa4c25abf2d01ad4c3078a541b4fd943514121/constrainmol/constrainmol.py#L30-L36

Although i dont think this handles the cases of angle constraints though.

**Comment by ramanishsingh** [comment]
Example jupyter notebook for using constrainmol for pentane.
Thanks to @bc118  for providing the mol2 and xml files.
https://gist.github.com/ramanishsingh/598f714e3a6063b996347c1ce68ddebf
Normal filled box has an accuracy of 1e-5 \AA with bond lengths, contrainmol makes it 1e-11 \AA
