### ISSUE TITLE
Box's build different initial atom coordinates when run on my Mac for Methane

### ISSUE THREAD

**Issue by bc118** [mosdef-hub/reproducibility_study#128]
Box's build different initial atom coordinates when run on my Mac for Methane, which yields different initial energies.

**Comment by bc118** [comment]
After some digging, it seems that reall issue is not GOMC related.  

When I build the system on my Mac, it gives me different coordinates than when I do it on my Desktop Red Hat or what is produced on your HPC (likely Red Hat)
.

**Comment by bc118** [comment]
Provided below are the signac state point, Mac built coordinates (.xyz) and RHEL built coordinates(.xyz).
[data.zip](https://github.com/mosdef-hub/reproducibility_study/files/7296422/data.zip)

**Comment by justinGilmer** [comment]
mwe to produce

```py3
import json
from reproducibility_project.src.molecules import system_builder
import pathlib

path = pathlib.path("~/signac_statepoint.json")
with open(path, 'r') as p:
    print(p)
    sp = json.load(p)
    print(sp)
    b1, b2 = system_builder.construct_system(sp)
    b1.save('test.xyz')
```
