### ISSUE TITLE
LJ tail correction

### ISSUE THREAD

**Issue by tcmoore3** [mosdef-hub/reproducibility_study#15]
Putting this here instead of on the spreadsheet. We need to be consistent with our handling of the LJ tail correction. If we are going to use it, we will have to implement it in HOOMD-blue. I know LAMMPS and GROMACS have switches for handling the LJ tail correction, but I'm not sure about the other engines.

**Comment by jennyfothergill** [comment]
This is resolved--planning to use no tail correction/smoothing functions (i.e., hard cutoff)
