### ISSUE TITLE
Updates to SPE for Foyer forcefield parameters

### ISSUE THREAD

**Issue by CalCraven** [mosdef-hub/reproducibility_study#236]
According to discussion with @ramanishsingh, the parameters used for the MCCCS components were take directly from the TraPPE website instead of the Foyer forcefield if it used the TraPPE UA model (methane, benzene, pentane). Due to minor 1e-4 truncation differences in epsilon parameters specified in K (TraPPE units) and in kJ/mol (Foyer units), the resulting forcefields are different enough to show differences in a single point energy calculation.

MethaneUA _CH4 epsilon:
TraPPE original is specified as 148.0K
TraPPE Foyer =1.23054 kJ/mol =  148.0018969973220K

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-1e03706c-7fff-c01a-c844-a1b3f34764a2"><p dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;"></p><div dir="ltr" style="margin-left:0pt;" align="left">

Engine | FF | Energy (K) | Energy (kj/mol) | Percentage diff w.r.t. LAMMPS
-- | -- | -- | -- | --
LAMMPS | TraPPE_foyer | - | 536743.553800000 | 0
MCCCS-MN | TraPPE_orig | 64554583.8347322 | 536736.674124320 | 0.001281744
MCCCS-MN | TraPPE_foyer | 64555411.2663036 | 536743.553773189 | 4.99513E-09

</div></b>

**Comment by ramanishsingh** [comment]
Completed: 
https://github.com/mosdef-hub/reproducibility_study/blob/main/reproducibility_project/spe_subproject/workspace/707f94b30741cf2ca7f3af07b7b07978/log-spe.txt
and
https://github.com/mosdef-hub/reproducibility_study/blob/main/reproducibility_project/spe_subproject/workspace/4cc18d76c5f8043b0c01eab67d0ed722/log-spe.txt
