### ISSUE TITLE
Molecules to study

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/reproducibility_study#3]
A table of molecules we plan to include in this study, as well as conditions. Edit as needed.

NOTE: This does not currently include any challenge molecules we discussed before.

| Molecules | Forcefield | Conditions | Ensembles | Reasoning |
| ---------- | ---------- | ----------- | ----------- | ---------- |
| United-Atom Methane | TraPPE-UA | 3 (T, rho), 3 (T,P) | NVT, NpT, GEMC-NVT | LJ only |
| United-Atom Ethane | TraPPE-UA | 1 (T, rho), 1 (T,P) | NVT, NpT | Adds bonds |
| United-Atom Propane | TraPPE-UA | 1 (T, rho), 1 (T,P) | NVT, NpT | Adds angles |
| United-Atom Butane | TraPPE-UA | 1 (T, rho), 1 (T,P) | NVT, NpT GEMC-NVT | Adds dihedrals |
| United-Atom Hexane | TraPPE-UA | 3 (T, rho), 3 (T,P) | NVT, NpT | Adds dihedrals and angles |
| SPC/E Water | SPC/E | 3 (T, rho), 3(T, P) | NVT, NpT | Electrostatics |
| Atomistic Ethanol | OPLS-AA | 3 (T, rho), 3 (T,P) | NVT, NpT | Adds dihedrals |

**Comment by jennyfothergill** [comment]
This information seems outdated. I'd like to move the molecules to a reference card in the Project board and close this issue. @bc118 @ramanishsingh if there is still an issue with the topic you mention, would you mind opening a new issue?

**Comment by bc118** [comment]
I dont think this is an issue, as we made a decision.  No need to reopen.  I will close
