### ISSUE TITLE
Add templates folder

### ISSUE THREAD

**Issue by jennyfothergill** [mosdef-hub/reproducibility_study#34]
Help everyone get set up on whichever cluster they use as well.

**Comment by jennyfothergill** [comment]
from chat with @bc118:
is there a way to add directives to an operation based on a conditional of the job? For example
```python
if job.sp.forcefield == "Trappe":
    directives.npu = 1
```

**Comment by ramanishsingh** [comment]
Don't know if this will work but I use something like this

```
@Project.operation
@Project.pre(has_md_files)
@Project.post(has_restart_file)
@flow.directives(np=72)
def run_md(job):
    from cp2kmdpy import runners_mpi
    import os

    with job:

        a = runners_mpi.run_md(job.doc.input_filename, job.doc.output_filename, 72)
        print(a)
```
Here I am using a directive to use 72 cores for an mpi job. 
There's also a directive for ngpu, so you can control the number of GPUs as well.

**Comment by ramanishsingh** [comment]
If you have very few number of cases, you can make separate operations for all those cases, each having a @project.pre condition that's only true for that case. 

for example
```python
@Project.label
def ff_is_trappe(job):
    """Check if TraPPE FF is being used."""
    return job.doc.FF=="TraPPE"
```
For this you will need to set job.doc.FF when you are setting up your simulations.

**Comment by tcmoore3** [comment]
> from chat with @bc118:
> is there a way to add directives to an operation based on a conditional of the job? For example
> 
> ```python
> if job.sp.forcefield == "Trappe":
>     directives.npu = 1
> ```

You can make the directives a `lambda` function that takes the job as the argument:
```
@Project.operation
@Project.pre(has_md_files)
@Project.post(has_restart_file)
@flow.directives(lambda job: {"Trappe": 1}.get(job.sp.forcefield, 0))
def run(job):
   # do stuff
``

**Comment by jennyfothergill** [comment]
added as of #60
