### ISSUE TITLE
Choose standard units. 

### ISSUE THREAD

**Issue by jennyfothergill** [mosdef-hub/reproducibility_study#38]
We should decide on a standard unit system to stick with for standard output.
It makes sense to me to stick with [foyer units](https://foyer.mosdef.org/en/stable/units.html).

Quantity | Units
-- | --
distance | nm
angle | radians
mass | amu
energy | kJ/mol

Let's make sure there's nothing missing and get consensus.  :)

**Comment by bc118** [comment]
I would rather the below, but I don't care either way.  I just never thought nm was the best unit for simulations.  I am likely the outlier.

Quantity | Units
-- | --
distance | Ang
angle | deg
mass | amu
energy | kcal/mol

-- | --
distance | nm
angle | radians
mass | amu
energy | kJ/mol

**Comment by tcmoore3** [comment]
+1 for nm, amu, and kJ/mol

**Comment by jennyfothergill** [comment]
These are added to references column in project board
