### ISSUE TITLE
Analysis TO-DOs

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/reproducibility_study#4]
- [ ] Fully define energy breakdowns for each simulation engine
- [x] Pick/write RDF analysis code
- [x] Pick/write diffusion coefficient code

**Comment by jennyfothergill** [comment]
As for diffusion coefficient, we could use [freud's MSD module](https://freud.readthedocs.io/en/latest/modules/msd.html). Looks like the diffusion coefficient can be estimated as 1/6 the slope of the MSD vs t. ([source](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3193570/))

**Comment by justinGilmer** [comment]
Oops, I missed this comment, sorry!

I more so meant that we need energy term decomposition in case we need to check energies between engines. Like breaking up potential energy into: NB (coul, LJ, etc), Bonded, etc.

Although that was more for the case if we had any issues with our properties. But I think at the moment this might not be necessary.
