### ISSUE TITLE
Equilibration and sampling

### ISSUE THREAD

**Issue by jennyfothergill** [mosdef-hub/reproducibility_study#41]
How should we decide that our systems are equilibrated and decorrelated?

- [x] Add [pymbar](https://pymbar.readthedocs.io/en/master/) to environment
- [x] Create a function that works on MD (using pymbar's [timeseries module](https://pymbar.readthedocs.io/en/master/timeseries.html) on the potential energy should work for MD)
- [x] Find a solution for equilibration/decorrelation times for MC

**Comment by justinGilmer** [comment]
`pymbar` has been added as of #48

**Comment by jennyfothergill** [comment]
after discussion with @ramanishsingh, pymbar's timeseries should also work for MC

**Comment by jennyfothergill** [comment]
resolved by #55, #48, and #56
