### ISSUE TITLE
Selectively delete workspace folder based on molecule

### ISSUE THREAD

**Issue by ramanishsingh** [mosdef-hub/reproducibility_study#44]
Given a molecule name (and/or engine name) delete all the statepoint folders from the workspace. 

Helpful when something goes wrong with the simulation of one molecule type and the workspace needs to be cleared up just for that molecule.

**Comment by jennyfothergill** [comment]
We can do this by combining some [signac command line args ](https://docs.signac.io/projects/core/en/latest/cli.html)
For example if I wanted to clear all the data in the job folder of the hoomd simulations:
```bash
signac rm -c $(signac find simulation_engine hoomd)
```
Or all of the methaneUA molecules:
```bash
signac rm -c $(signac find molecule methaneUA)
```
The `-c` flag to rm means that the job folder (the long hash of alphanumeric chars) isn't deleted, it's just cleared out.

**Comment by ramanishsingh** [comment]
Thanks! It works for me. Closing this issue.
