### ISSUE TITLE
add liquid and vapor densities and N_molecules and pressure to init.py

### ISSUE THREAD

**Issue by bc118** [mosdef-hub/reproducibility_study#50]
We need to add to following  (MD can ignore the vapor data):
- liquid and vapor densities
-  liquid and vapor N_molecules 
- pressure
- trappe-like FF (benzene FF) in forcefield section

**Comment by justinGilmer** [comment]
I think I added most of that with #49 

and do we need the densities if we can calc them with the box volume and N molecules and weight?

**Comment by bc118** [comment]
box length or density

**Comment by justinGilmer** [comment]
Ok here is the current infomation included in the statepoint as of #49 

- molecule
- engine
- replica
- temperature
- pressure
- ensemble
- N_liquid
- N_vap
- box_L_liq
- box_L_vap
- mass
- forcefield_name

Anything else we need? 

NOTE: `N_vap` and `box_L_vap` are `null` in the statepoint if it does not apply to the engine or ensemble

**Comment by justinGilmer** [comment]
Closed by #49
