### ISSUE TITLE
Add forcefields to init

### ISSUE THREAD

**Issue by jennyfothergill** [mosdef-hub/reproducibility_study#61]
Right now the forcefields are not filled in the job statepoints. Because the Forcefield object is not serializable, it makes the most sense to me to use either a string or the path to an xml file. I lean towards string. Then we could do something like
```
if job.sp.forcefield == "OPLSAA":
    ff = foyer.forcefields.load_OPLSAA()
elif job.sp.forcefield == "TRAPPE":
    ff = foyer.forcefields.Forcefield("path/to/benzene_trappe-ua_like.xml")
```
also, are we using the [included trappe xml](https://github.com/mosdef-hub/reproducibility_study/blob/main/reproducibility_project/src/xmls/benzene_trappe-ua_like.xml) for benzene only?

**Comment by justinGilmer** [comment]
For the trappe xml, yes that xml is just for the benzene molecule.

and I am pretty sure job.sp.forcefield is in each statepoint. Its under `forcefield_name`

Although I am totally in agreement with the ff loading step you included above.

**Comment by jennyfothergill** [comment]
oops. 🤦‍♀️ I misread the init file. I see now that the forcefield name is included. Side note: the squashiness caused by the nested for-loops makes the init file a little hard to read,

**Comment by justinGilmer** [comment]
I actually did not think about using the itertools product once I modified the data. im going to test that and see if it works as expected. That would be much nicer!
