### ISSUE TITLE
How to handle jobs that don't pass `is_equilibrated` after completion.

### ISSUE THREAD

**Issue by chrisjonesBSU** [mosdef-hub/reproducibility_study#64]
As we're making progress on some of the post-simulation analysis workflow, one of the added features is testing if a simulation is considered equilibrated given a threshold (#55 #56 ).  Right now, if it fails that test we get an error raised, but nothing else happens.  We should probably discuss how to handle restarting a job in this scenario.

**Comment by justinGilmer** [comment]
Here are a few thoughts I am piecing together.

The `analysis.equilibration.is_equilibrated` method will only error out if the `threshold` fraction of equilibrated data is less than we expect (if we pass in a `threshold` value of 0.8, this means we want to only throw away the first 20% or less of the data to equilibration "burn in"). If that is not the case, it returns `[False, t0, g]`

So I think we can leverage that as a label in our analysis.py project or something to this effect. Although there might be better ways to handle this.

```python3
from reproducibility_project.src.analysis.equilibration import is_equilibrated
@Project.label
@Project.pre(lambda job:  job.is_file('density.txt')) # can someone verify that i am using the lambda correctly here?
@with_job
def density_equilibrated(job):
    a_t = np.loadtxt("density.txt",...)
    return is_equilibrated(a_t, threshold=0.75)[0] # will return True or False
```

**Comment by justinGilmer** [comment]
Also including @jennyfothergill 's comments from her pr #60 

> check how to update restart logic. We used to use HOOMD_WALLTIME_STOP env variable, does it still work?

**Comment by jennyfothergill** [comment]
check out #94 for an example workflow of how I've handled this with HOOMD

**Comment by jennyfothergill** [comment]
I think this issue can be closed.
