### ISSUE TITLE
How do we want to access processed data from simulation trajectories?

### ISSUE THREAD

**Issue by CalCraven** [mosdef-hub/reproducibility_study#65]
We need a way to store processed data (for now rdf's, densities, etc.) and keep that in this repo for further analysis. This needs to make sure that the trajectory information can be easily accessed for each simulation engine, but to make sure that none of the trajectory information itself is pushed to this repository due to data storage concerns.

My first thought was to have the workspace folder be saved to the git repo, but keep all of the trajectory information in the .gitignore so only the processed files would be tracked by git. We could also just have an entire separate directory to copy the information over and be accessible to the analysis routines. That could also be separated by job or by simulation engine, or even by molecule. Anyone have any suggestions?

**Comment by jennyfothergill** [comment]
related to #28

**Comment by jennyfothergill** [comment]
>My first thought was to have the workspace folder be saved to the git repo, but keep all of the trajectory information in the .gitignore so only the processed files would be tracked by git. 

This seems reasonable to me. The hashed job folder names will be the same across systems (as long as we don't modify the statepoints).

>We could also just have an entire separate directory to copy the information over and be accessible to the analysis routines. That could also be separated by job or by simulation engine, or even by molecule. Anyone have any suggestions?

This also seems worable--I would recommend we use something like a bash with signac cli to manage this folder because manually copying could be annoying.

**Comment by CalCraven** [comment]
Just to continue this discussion, it looks like all of our workspace trajectory information will be stored via Michigan's dropbox account information (thanks to @kjcoulter). So at least we can all also run the analysis scripts and save output to the workspace folders that you are working with. That at least gives us a starting place to have access to this information.

**Comment by CalCraven** [comment]
Closing this issue, seems that the solution is through a combination of rclone and dropbox, it is really easy to store this information remotely.
