### ISSUE TITLE
Sampling rates

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/reproducibility_study#75]
What sampling rates do we want to use for our properties and trajectories in our simulations?

### NOTE: Suggestions for MD
trajectory_sample_rate: 10000 timesteps
property_sample_rate: 1000 timesteps

Just a generic guess at first, but the sooner we decide on this the better. I think @bc118 mentioned that the MC folks have defined values for their sims already.

**Comment by bc118** [comment]
The Mc sampling and running values are listed in the excel sheet

**Comment by jennyfothergill** [comment]
That sounds good to me--right now hoomd is running with 10,000 (trajectory) and 5,000 (property) as the interval between samples, but it's easy to change. :)

**Comment by jennyfothergill** [comment]
I've added these intervals to [the project board](https://github.com/mosdef-hub/reproducibility_study/projects/1#card-66677615)
