### ISSUE TITLE
What constraints are needed for MD simulations? 

### ISSUE THREAD

**Issue by daico007** [mosdef-hub/reproducibility_study#84]
I am running into some issues when using with `constraints = all-angles` for a box of ethanol in GROMACS (with the LINCS algorithm). The simulation ran fine with `constraints = all-bonds`, so I am just wondering what is the appropriate constraints we should use for the project or for MD specifically?

**Comment by daico007** [comment]
Our simulations are having issues with constraints (too many warnings), so I think we gonna edit to production run to remove the constraints.

**Comment by jennyfothergill** [comment]
I think this issue can be closed. Constraint parameters for water are documented in the [project doc](https://github.com/mosdef-hub/reproducibility_study/projects/1)--although HOOMD uses a completely rigid model for water. Benzene is also rigid. Pentane has two models and one has constrained bonds. To my knowledge, no constraints are applied to ethanol.
