### ISSUE TITLE
Include Compound JSON files in each statepoint

### ISSUE THREAD

**Issue by justinGilmer** [mosdef-hub/reproducibility_study#87]
For each statepoint, to ensure that we can get back the exact same mbuild Compound for future studies, we should also save out a JSON serialization of each mBuild compound.

For example:
`filled_system.save("starting_compound.json")`

This will ensure that we preserve the hierarchy of the compounds, and any other information that is unique to mBuild.

This can happen at the same time as the other file io when writing out the systems for our engines.

**Comment by CalCraven** [comment]
This is done for the lammps stuff!

**Comment by jennyfothergill** [comment]
This is done for hoomd as of 9140dc1

**Comment by jennyfothergill** [comment]
I think this can be closed as well--we could add a note to the project board if needed
