### ISSUE TITLE
Option to change log filename in `plot_job_property_with_t0`

### ISSUE THREAD

**Issue by ramanishsingh** [mosdef-hub/reproducibility_study#89]
Currently the function only reads file named "log.txt".
This might not work for systems with two boxes, where we have something like "log_box1.txt", and "log_box2.txt".
New optional argument, `log_filename` can be introduced in the function.

**Comment by CalCraven** [comment]
Similar issue in #97. Should we write a comprehensive list of file naming conventions we want to follow?

**Comment by justinGilmer** [comment]
I think we should. I am also including some generic methods that default to certain expected names, but since we are trying to make the analysis routines all standardized using the `analysis-project.py` file, I think a standard naming convention is necessary.

**Comment by CalCraven** [comment]
Does [this](https://github.com/mosdef-hub/reproducibility_study/projects/1#card-67959147) sound reasonable?

**Comment by jennyfothergill** [comment]
@CalCraven , the link doesn't work for me, but I see the card you added in the project board and that sounds very reasonable. I am opening a PR to add more flexibility to the analysis functions right now.
