### ISSUE TITLE
NaN values from `is_equilibrated`?

### ISSUE THREAD

**Issue by jennyfothergill** [mosdef-hub/reproducibility_study#92]
My NPT sim is clearly not equilibrated at the beginning and maybe my pressure coupling is too high (guessing from the initial oscillations in volume, see attached plots of volume vs timestep), but eventually it appears that the simulation volume equilibrates. I would think that this kind of data would be fine for pymbar, but if the whole run is used, I get NaN values:
![image](https://user-images.githubusercontent.com/39961845/131396923-d8cc6086-1ec9-4417-aa83-79afd55ed15c.png) 
![image](https://user-images.githubusercontent.com/39961845/131396888-7ece8fed-fed2-40c6-848f-6391d615c6dc.png)

It's odd though because if I chop of the first 50 values, `is_equilibrated` works as expected. what should be the standard procedure for choosing where to start this equilibration analysis? I'm including my logfile in case anyone wants to test for themselves.
[log-npt.txt](https://github.com/mosdef-hub/reproducibility_study/files/7079280/log-npt.txt)

**Comment by justinGilmer** [comment]
It looks like your txt file is malformed. There are multiple entries for the title in the first 50 or so entries. I think that is the cause of the issues. 
I removed the two extra headers (but left the wonky data there which seems to be the source of the major oscillations), and the results from that seem reasonable

**Comment by jennyfothergill** [comment]
Oops 🤦‍♀️ Thank you so much for your help!
