### ISSUE TITLE
Trajectory Name For Diffusion Calculations

### ISSUE THREAD

**Issue by CalCraven** [mosdef-hub/reproducibility_study#97]
Looking at the calculation for RDF and for diffusion, both apply their analysis for default trajectory names of `trajectory.gsd`. However, the diffusion calculation needs to be applied to an NVT production simulation, whereas the RDF does not have that stipulation. Unless the plan is to also do all of our analysis from the NVT simulation, instead of the "production" simulation that is in NPT, we might want to allow for a keyword to be passed to these [analysis routines](https://github.com/mosdef-hub/reproducibility_study/blob/main/reproducibility_project/src/analysis/rdf.py) to make sure the correct trajectory is grabbed. It also might be nice to add to the project some guidelines for naming conventions so we all keep relatively similar.

Here are links to the relevant lines of code:
https://github.com/mosdef-hub/reproducibility_study/blob/8b24e488fb0e7e431792c939ed4c145004d80d0a/reproducibility_project/src/analysis/rdf.py#L42
https://github.com/mosdef-hub/reproducibility_study/blob/8b24e488fb0e7e431792c939ed4c145004d80d0a/reproducibility_project/src/analysis/diffusion.py#L43

**Comment by jennyfothergill** [comment]
I agree--when I wrote these, I had less of a grasp on the whole project and I used this as a placeholder. 
In hoomd I am using the names "trajectory-npt.gsd", "trajectory-nvt.gsd", and "log-npt.txt", "log-nvt.txt".

related to #89

**Comment by jennyfothergill** [comment]
fixed by #101
